# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IvyLeeMethod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IvyLeeMethod
pod 'Google-Mobile-Ads-SDK'
pod 'FSCalendar'
pod 'CalculateCalendarLogic'
pod 'RealmSwift'

  target 'IvyLeeMethodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IvyLeeMethodUITests' do
    # Pods for testing
  end

end
